#!/bin/sh
# Jon Ward, 2025.
# Force-kill a process in either Linux or WSL.

. "$HOME/.config/shell/lib/system.sh"

is_alive() {
	if is_wsl; then
		tasklist.exe /FI "IMAGENAME EQ $1" | grep -q "$1"
	else
		pgrep -x "$1" >/dev/null
	fi

	return $?
}

force_kill() {
	if [ $# -eq 0 ]; then
		printf "Usage: %s [process]\n" "$(basename "$0")"
		return 1
	fi

	process="$1"
	sleep_time=1
	tries=1

	if ! is_alive "$process"; then
		printf "Process '%s' not found.\n" "$process" 
		return 0
	fi

	# Check if WSL and set command to kill process accordingly
	if is_wsl; then
		process="$process.exe"
		kill_cmd="taskkill.exe /T /IM $process"
		force_kill_cmd="taskkill.exe /F /T /IM $process"
	else
		kill_cmd="pkill -x $process"
		force_kill_cmd="pkill -9 -x $process"
	fi

	# Terminate gracefully
	i=1
	while [ "$i" -le "$tries" ]; do
		printf "Attempt %s/%s to terminate '%s'...\n" "$i" "$tries" "$process"
		$kill_cmd
		sleep $sleep_time

		if ! is_alive "$process"; then
			printf "Process '%s' terminated.\n" "$process" 
			return 0
		fi

		i=$((i + 1))
	done

	# Terminate forcefully
	printf "\nGraceful termination failed.	Force-killing...n"
	$force_kill_cmd

	if is_alive "$process"; then
		printf "Error: Failed to terminate '%s'.\n" "$process" >&2
		return 1
	else
		printf "Success: '%s' terminated.\n" "$process"
		return 0
	fi
}

force_kill "$@"

