#!/bin/sh
# Jon Ward, 2025.
# Update all the things

. "$HOME/.config/shell/lib/install-update-helpers.sh"

update_everything() {
	detect_package_manager || exit 1

	update_system_packages
	update_yt_dlp
	update_arkenfox
	update_npm_packages
	update_rust_toolchain
	update_rust_crates
	install_git_prompt

	# This must come last, because it will kill WSL
	if is_wsl; then
		update_wsl
	fi
}

update_everything

